#
#  For more information, please see: http://software.sci.utah.edu
# 
#  The MIT License
# 
#  Copyright (c) 2009 Scientific Computing and Imaging Institute,
#  University of Utah.
# 
#  
#  Permission is hereby granted, free of charge, to any person obtaining a
#  copy of this software and associated documentation files (the "Software"),
#  to deal in the Software without restriction, including without limitation
#  the rights to use, copy, modify, merge, publish, distribute, sublicense,
#  and/or sell copies of the Software, and to permit persons to whom the
#  Software is furnished to do so, subject to the following conditions:
# 
#  The above copyright notice and this permission notice shall be included
#  in all copies or substantial portions of the Software. 
# 
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
#  OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#  DEALINGS IN THE SOFTWARE.
#

SET(IMPORTER_LIBRARY_LIST "" CACHE INTERNAL "list of libraries" FORCE)
SET(IMPORTER_LIST "" CACHE INTERNAL "list of importers" FORCE)

SET(EXPORTER_LIBRARY_LIST "" CACHE INTERNAL "list of libraries" FORCE)
SET(EXPORTER_LIST "" CACHE INTERNAL "list of importers" FORCE)


MACRO(ADD_LIBRARY_IMPORTERS library)
  SET(IMPORTER_LIBRARY_LIST_TEMP ${IMPORTER_LIBRARY_LIST} ${library})
  SET(IMPORTER_LIBRARY_LIST ${IMPORTER_LIBRARY_LIST_TEMP} CACHE INTERNAL "list of libraries")

  SET(IMPORTER_LIST_TEMP ${IMPORTER_LIST} ${ARGN})
  SET(IMPORTER_LIST ${IMPORTER_LIST_TEMP} CACHE INTERNAL "list of importers")
ENDMACRO(ADD_LIBRARY_IMPORTERS)

MACRO(ADD_LIBRARY_EXPORTERS library)
  SET(EXPORTER_LIBRARY_LIST_TEMP ${EXPORTER_LIBRARY_LIST} ${library})
  SET(EXPORTER_LIBRARY_LIST ${EXPORTER_LIBRARY_LIST_TEMP} CACHE INTERNAL "list of libraries")

  SET(EXPORTER_LIST_TEMP ${EXPORTER_LIST} ${ARGN})
  SET(EXPORTER_LIST ${EXPORTER_LIST_TEMP} CACHE INTERNAL "list of exporters")
ENDMACRO(ADD_LIBRARY_EXPORTERS)


MACRO(BUILD_REGISTER_IMPORTEREXPORTER_LIBRARY)

  SET(IMPORTERLIST "")
  FOREACH(IMPORTER ${IMPORTER_LIST})
    GET_FILENAME_COMPONENT(IMPORTERFILE ${IMPORTER} NAME_WE)
    SET(IMPORTERLIST ${IMPORTERLIST} ${IMPORTERFILE})
  ENDFOREACH(IMPORTER ${IMPORTER_LIST})
  LIST(REMOVE_DUPLICATES IMPORTERLIST)

  SET(EXPORTERLIST "")
  FOREACH(EXPORTER ${EXPORTER_LIST})
    GET_FILENAME_COMPONENT(EXPORTERFILE ${EXPORTER} NAME_WE)
    SET(EXPORTERLIST ${EXPORTERLIST} ${EXPORTERFILE})
  ENDFOREACH(EXPORTER ${EXPORTER_LIST})
  LIST(REMOVE_DUPLICATES EXPORTERLIST)

  SET(DECLARATIONS "")
  SET(IMPLEMENTATIONS "")

  FOREACH(IMPORTER ${IMPORTERLIST})
    STRING(CONFIGURE "extern void register_importer_@IMPORTER@();\n" DECLARATION)
    SET(DECLARATIONS "${DECLARATIONS} ${DECLARATION}")

    STRING(CONFIGURE "  register_importer_@IMPORTER@();\n" IMPLEMENTATION)
    SET(IMPLEMENTATIONS "${IMPLEMENTATIONS} ${IMPLEMENTATION}")
  ENDFOREACH(IMPORTER ${IMPORTERLIST})


  FOREACH(EXPORTER ${EXPORTERLIST})
    STRING(CONFIGURE "extern void register_exporter_@EXPORTER@();\n" DECLARATION)
    SET(DECLARATIONS "${DECLARATIONS} ${DECLARATION}")

    STRING(CONFIGURE "  register_importer_@EXPORTER@();\n" IMPLEMENTATION)
    SET(IMPLEMENTATIONS "${IMPLEMENTATIONS} ${IMPLEMENTATION}")
  ENDFOREACH(EXPORTER ${EXPORTERLIST})
    
  CONFIGURE_FILE(${CMAKE_CURRENT_SOURCE_DIR}/Configuration/ImporterExporterLibraryInit.h.in
                 ${CMAKE_CURRENT_BINARY_DIR}/Init/ImporterExporterLibraryInit.h
                 @ONLY)
                 
ENDMACRO(BUILD_REGISTER_IMPORTEREXPORTER_LIBRARY)
