/*
 For more information, please see: http://software.sci.utah.edu

 The MIT License

 Copyright (c) 2016 Scientific Computing and Imaging Institute,
 University of Utah.


 Permission is hereby granted, free of charge, to any person obtaining a
 copy of this software and associated documentation files (the "Software"),
 to deal in the Software without restriction, including without limitation
 the rights to use, copy, modify, merge, publish, distribute, sublicense,
 and/or sell copies of the Software, and to permit persons to whom the
 Software is furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included
 in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 DEALINGS IN THE SOFTWARE.
*/

// Qt includes
#include <QtGui/QColor>

// Interface configuration
#include "InterfaceConfiguration.h"

// Interface includes
#include <Interface/Application/StyleSheet.h>

// Set the accent color of the application
#define ACCENT_COLOR INTERFACE_ACCENT_COLOR
#define ACCENT_HEX_COLOR INTERFACE_ACCENT_HEX_COLOR
#define ACCENT_BRIGHT_COLOR INTERFACE_ACCENT_BRIGHT_COLOR
#define ACCENT_BRIGHT_HEX_COLOR INTERFACE_ACCENT_BRIGHT_HEX_COLOR
#define BACKGROUND_COLOR "71, 71, 74"
#define PALETTE_BACKGROUND_COLOR "106, 106, 112"
#define ALTERNATE_BACKGROUND_COLOR "100, 100, 106"
#define FORM_BACKGROUND_COLOR "43, 43, 46"
#define LARGE_FORM_BACKGROUND_COLOR "226, 223, 236"
#define FONT_COLOR "255, 255, 255"
#define LARGE_FORM_FONT_COLOR "0, 0, 0"
#define BORDER_COLOR "49, 49, 52"
#define HOVER_COLOR "91, 91, 94"
#define SELECT_COLOR "49, 49, 52"
#define FOOTER_COLOR "22, 22, 25"
#define INACTIVE_COLOR "82, 82, 86"
#define ALERT_BACKGROUND_COLOR "204, 78, 78"
#define CRITICAL_ERROR_COLOR "255, 89, 89"
#define ERROR_COLOR "242, 93, 93"
#define WARNING_COLOR "242, 113, 0"
#define MESSAGE_COLOR ACCENT_BRIGHT_COLOR
#define SUCCESS_COLOR ACCENT_BRIGHT_COLOR
#define DEBUG_COLOR "purple"
#define CRITICAL_ERROR_HEX_COLOR "#FF5959"
#define ERROR_HEX_COLOR "#F25D5D"
#define WARNING_HEX_COLOR "#F27100"
#define MESSAGE_HEX_COLOR ACCENT_BRIGHT_HEX_COLOR
#define SUCCESS_HEX_COLOR ACCENT_BRIGHT_HEX_COLOR

#define PALETTE_BACKGROUND_PROPERTY "use_palette_background"

namespace Seg3D
{
  const QString StyleSheet::BACKGROUND_COLOR_STR = BACKGROUND_COLOR;

  const char* StyleSheet::PALETTE_BACKGROUND_PROPERTY_C = PALETTE_BACKGROUND_PROPERTY;

  const QString StyleSheet::MAIN_STYLE_C = QString::fromUtf8(
   "QMainWindow{"
   " background-color: rgb( " BACKGROUND_COLOR ") ;"
   " border: 0px solid rgb( " BORDER_COLOR ") ;"
   " border-radius: 3px;"
   " color: rgb( " FONT_COLOR ") ;"
   "}"
   "QMainWindow::separator{"
   " background-color: rgb( " BACKGROUND_COLOR ") ;"
   "}"
   "QWidget {"
   " outline: none;"
   "}"
  // to explicitly take these colors set this property for an object ala:
  //   this->setProperty(StyleSheet::PALETTE_BACKGROUND_PROPERTY_C, false);
  "QWidget[" PALETTE_BACKGROUND_PROPERTY "=false] > QWidget{"
  " background-color: rgb( " BACKGROUND_COLOR ") ;"
  " border: 3px solid rgb( " BORDER_COLOR ") ;"
  " border-radius: 3px;"
  " color: rgb( " FONT_COLOR ") ;"
  "}"
  // to explicitly use the palette background set this property for an object ala:
  //   this->setProperty(StyleSheet::PALETTE_BACKGROUND_PROPERTY_C, true);
  "QWidget[" PALETTE_BACKGROUND_PROPERTY "=true] > QWidget{"
  " background-color: rgb( " PALETTE_BACKGROUND_COLOR ") ;"
  " border: 3px solid rgb( " BORDER_COLOR ") ;"
  " color: rgb( " FONT_COLOR ") ;"
  " border-radius: 3px;"
  "}"
   // Style the border that appears outside certain widgets to show that widget has focus
  "QFocusFrame{"
  " border: 4px solid rgb( " ACCENT_COLOR ") ;"
  " border-radius: 3px;"
  " padding: 0px;"
  "}"
  "QWizard QFrame{"
  " background-color: rgb( " BACKGROUND_COLOR ") ;"
  " border: none;"
  "}"
  "QDockWidget{"
  " background-color: rgb( " BACKGROUND_COLOR ") ;"
  " color: rgb( " FONT_COLOR ") ;"
  " titlebar-close-icon: url(:/General_Icons/exit.png);"
  " titlebar-normal-icon: url(:/General_Icons/maximize.png);"
  "}"
  "QDockWidget > QWidget{"
  " border: none;"
  " padding: 3px;"
  " margin: 0px;"
  "}"
  // using dock_base_ here because of Qt bug where
  // setting QDockWidget background-color does nothing
  // for docked widgets (works for floating)
  "QWidget#dock_base_ QWidget#dockWidgetContents{"
  " background-color: rgb( " BACKGROUND_COLOR ") ;"
  "}"
  "QDockWidget::title {"
  " background-color: rgb( " BACKGROUND_COLOR ") ;"
  " text-align: left center;"
  " subcontrol-position: top left;"
  " subcontrol-origin: margin;"
  " position: absolute;"
  " padding: 2px;"
  " padding-left: 4px;"
  "}"
  "QDockWidget::close-button {"
  " subcontrol-position: top right;"
  " subcontrol-origin: margin;"
  " position: absolute;"
  " right: 4px;"
  " width: 14px;"
  " border: none;"
  " padding: 0px;"
  " background: rgb( " BACKGROUND_COLOR ") ;"
  " icon-size: 8px;"
  "}"
 "QDockWidget::float-button{"
  " subcontrol-position: top right;"
  " subcontrol-origin: margin;"
  " position: absolute;"
  " right: 20px;"
  " width: 14px;"
  " border: none;"
  " padding: 0px;"
  " background: rgb( " BACKGROUND_COLOR ") ;"
  " icon-size: 8px;"
  "}"
  "QScrollBar:horizontal {"
  " border: none;"
  " background: rgba(" HOVER_COLOR ",150);"
  " height: 10px;"
  " margin: 0px;"
  " padding: 0px 2px 0px 2px;"
  " border-radius: 3px;"
  "}"
  "QScrollBar:horizontal:hover {"
  " background: rgba(" HOVER_COLOR ",255);"
  "}"
  "QScrollBar::handle:horizontal {"
  " background-color:qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1,"
  "  stop:0 rgba(179, 179, 179, 200), "
  "  stop:1 rgba(123, 123, 123, 200));"
  " border-radius: 3px;"
  " min-width: 20px;"
  "}"
  "QScrollBar::handle:horizontal:hover {"
  " background-color:qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1,"
  "  stop:0 rgba(179, 179, 179, 255), "
  "  stop:1 rgba(123, 123, 123, 255));"
  "}"
  "QScrollBar::add-line:horizontal {"
  " background-color: rgb(" ALTERNATE_BACKGROUND_COLOR ") ;"
  " width: 0px;"
  " subcontrol-position: right;"
  " subcontrol-origin: margin;"
  "}"
  "QScrollBar::sub-line:horizontal {"
  " background-color: rgb(" ALTERNATE_BACKGROUND_COLOR ") ;"
  " width: 0px;"
  " subcontrol-position: right;"
  " subcontrol-origin: margin;"
  "}"
  "QScrollBar:vertical {"
  " border: none;"
  " background-color: rgba(" HOVER_COLOR ",150);"
  " width: 10px;"
  " margin: 0px;"
  " padding: 2px 0px 2px 0px;"
  " border-radius: 3px;"
  "}"
  "QScrollBar:vertical:hover {"
  " background-color: rgba(" HOVER_COLOR ",255);"
  "}"
  "QScrollBar::handle:vertical {"
  " background-color:qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5,"
  "  stop:0 rgba(179, 179, 179, 200), "
  "  stop:1 rgba(123, 123, 123, 200));"
  " border-radius: 3px;"
  " min-height: 20px;"
  "}"
  "QScrollBar::handle:vertical:hover {"
  " background-color:qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5,"
  "  stop:0 rgba(179, 179, 179, 255), "
  "  stop:1 rgba(123, 123, 123, 255));"
  "}"
  "QScrollBar::add-line:vertical {"
  " background-color: rgb(" ALTERNATE_BACKGROUND_COLOR ") ;"
  " width: 0px;"
  " subcontrol-position: bottom;"
  " subcontrol-origin: margin;"
  "}"
  "QScrollBar::sub-line:vertical {"
  " background-color: rgb(" ALTERNATE_BACKGROUND_COLOR ") ;"
  " width: 0px;"
  " subcontrol-position: top;"
  " subcontrol-origin: margin;"
  "}"
  "QSplitter::handle {"
  " image: url(:/General_Icons/radio-empty.png);"
  "}"
  "QSplitter::handle:vertical {"
   " height: 6px;"
   " background:rgb( " BACKGROUND_COLOR ") ;"
  "}"
  "QSplitter::handle:horizontal {"
   " width: 6px;"
   " background:rgb( " BACKGROUND_COLOR ") ;"
  "}"
  "QSplitter::handle:pressed {"
  " image: url(:/General_Icons/radio-fill.png);"
  "}"
  "QToolTip{"
  " color: rgb( " FONT_COLOR ") ;"
  " background-color: rgb( " BACKGROUND_COLOR ") ;"
  " border: 2px solid rgb( " BORDER_COLOR ") ;"
  " border-radius: 3px;"
  " outline: none;"
  "}"
  "QLabel{"
  " color: rgb( " FONT_COLOR ") ;"
  " outline: none;"
  "}"
  "QLabel#message_ {"
  " color: rgb(" FONT_COLOR ");"
  " font: bold;"
  "}"
  "QWidget#message_alert_ {"
  " border-radius:3px;"
  " background-color: rgb(" ALERT_BACKGROUND_COLOR ");"
  "}"
  "QDialog{"
  " background-color: rgb( " BACKGROUND_COLOR ") ;"
  " border: none;"
  " border-radius: 3px;"
  " color: rgb( " FONT_COLOR ") ;"
  "}"
  "QMenu{"
  " background-color:rgb( " PALETTE_BACKGROUND_COLOR ") ;"
  " color: rgb( " FONT_COLOR ") ;"
  " selection-background-color: rgb( " SELECT_COLOR ") ; "
  " selection-color: rgb( " FONT_COLOR ") ; "
  "}"
  "QStatusBar{"
  " background-color: rgb( " SELECT_COLOR ") ;"
  "}"
  "QTabWidget{"
  " background-color: rgb( " BACKGROUND_COLOR ") ;"
  " border: none;"
   "}"
  "QTabWidget::tab-bar{"
  " alignment: center;"
   "}"
  "QTabWidget::pane{"
  " background-color: rgb( " BACKGROUND_COLOR ") ;"
  " border: 2px solid rgb( " BORDER_COLOR ") ;"
  " position: absolute;"
  " top: -0.5em;"
  " padding-top: 8px;"
  " margin: 4px;"
  " margin-bottom: 8px;"
  " margin-top: 0px;"
  "}"
   "QTabBar::tab:!selected{"
   " color: rgb( " FONT_COLOR ") ;"
   " background-color: rgb( " INACTIVE_COLOR ") ;"
   " border: 1px solid rgb( " BORDER_COLOR ") ;"
   " padding: 2px;"
   "}"
  "QTabBar::tab:selected{"
   " color: rgb( " FONT_COLOR ") ;"
   " background-color: rgb( " SELECT_COLOR ") ;"
   " border: 1px solid rgb( " BORDER_COLOR ") ;"
   " padding: 2px;"
   "}"
  "QWidget#tool_dock_ QTabWidget{"
  " background-color: rgb( " PALETTE_BACKGROUND_COLOR ") ;"
  " border: none;"
   "}"
  "QWidget#tool_dock_ QTabWidget::pane{"
  " background-color: rgb( " PALETTE_BACKGROUND_COLOR ") ;"
  " border: 2px solid rgb( " BORDER_COLOR ") ;"
  "}" 
   "QHeaderView {"
   " background-color: rgb( " PALETTE_BACKGROUND_COLOR ") ;"
   " color: rgb( " FONT_COLOR ") ;"
   " border: none;"
  "}"
   "QHeaderView::section {"
   " background-color: rgb( " BACKGROUND_COLOR ") ;"
   " color: rgb( " FONT_COLOR ") ;"
   " border: 1px solid rgb(" HOVER_COLOR ");"
   " border-left: none;"
   " border-top: none;"
   " padding-left: 5px;"
   " padding-right: 5px;"
  "}"
   "QHeaderView::section:first {"
   " background-color: rgb( " BACKGROUND_COLOR ") ;"
   " color: rgb( " FONT_COLOR ") ;"
   " border: 1px solid rgb(" HOVER_COLOR ");"
   " border-top: none;"
   " border-left: none;"
   " padding-left: 5px;"
   " padding-right: 5px;"
  "}"
   "QHeaderView::section:last {"
   " background-color: rgb( " BACKGROUND_COLOR ") ;"
   " color: rgb( " FONT_COLOR ") ;"
   " border: 1px solid rgb(" HOVER_COLOR ");"
   " border-top: none;"
   " border-left: none;"
   " border-right: none;"
   " padding-left: 5px;"
   " padding-right: 5px;"
  "}"
   "QHeaderView::section:selected {"
   " background-color: rgb( " SELECT_COLOR ") ;"
   " color: rgb( " FONT_COLOR ") ;"
   " border: none;"
  "}"
  "QAbstractItemView::item{"
  " selection-background-color: rgb( " SELECT_COLOR ") ;"
  " selection-color: rgb( " FONT_COLOR ") ;"
  "}"
  "QAbstractItemView::item:selected{"
  " background-color: rgb( " SELECT_COLOR ") ;"
  "}"
  "QListWidget{"
  " background-color: rgb( " PALETTE_BACKGROUND_COLOR ") ;"
  " alternate-background-color: rgb( " ALTERNATE_BACKGROUND_COLOR ") ;"
  " selection-background-color: rgb( " SELECT_COLOR ") ;"
  " border: none;"
  " color: rgb( " FONT_COLOR ") ;"
  " selection-color: rgb( " FONT_COLOR ") ;"
  "}"
  "QListWidget::indicator {"
  " width: 13px;"
  " height: 13px;"
  "}"
  "QListWidget::indicator:unchecked {"
  " image: url(:/General_Icons/checkbox-unselected.png);"
  "}"
  "QListWidget::indicator:indeterminate {"
  " image: url(:/General_Icons/checkbox-indeterminate.png);"
  "}"
  "QListWidget::indicator:checked {"
  " image: url(:/General_Icons/checkbox-selected.png);"
  "}"
  "QListView{"
  " background-color: rgb( " PALETTE_BACKGROUND_COLOR ") ;"
  " alternate-background-color: rgb( " ALTERNATE_BACKGROUND_COLOR ") ;"
  " selection-background-color: rgb( " SELECT_COLOR ") ;"
  " border: none;"
  " color: rgb( " FONT_COLOR ") ;"
  " selection-color: rgb( " FONT_COLOR ") ;"
  " outline: none;"
  "}"
  "QListView::item:selected{"
  " background-color: rgb( " SELECT_COLOR ") ;"
  "}"
  "QTableWidget{"
  " background-color: rgb( " PALETTE_BACKGROUND_COLOR ") ;"
  " alternate-background-color: rgb( " ALTERNATE_BACKGROUND_COLOR ") ;"
  " selection-background-color: rgb( " SELECT_COLOR ") ;"
  " border: none;"
  " color: rgb( " FONT_COLOR ") ;"
  " selection-color: rgb( " FONT_COLOR ") ;"
  "}"
  "QTableView{"
  " background-color: rgb( " PALETTE_BACKGROUND_COLOR ") ;"
  " alternate-background-color: rgb( " ALTERNATE_BACKGROUND_COLOR ") ;"
  " selection-background-color: rgb( " SELECT_COLOR ") ;"
  " border: none;"
  " color: rgb( " FONT_COLOR ") ;"
  " selection-color: rgb( " FONT_COLOR ") ;"
  " outline: none;"
  "}"
  "QTableView::item:selected{"
  " background-color: rgb( " SELECT_COLOR ") ;"
  "}"
  "QTableView QTableCornerButton::section{"
  " background-color: rgb( " BACKGROUND_COLOR ") ;"
  " color: rgb( " FONT_COLOR ") ;"
  " border: 1px solid rgb(" HOVER_COLOR ");"
  " border-left: none;"
  " border-top: none;"
  " padding-left: 5px;"
  " padding-right: 5px;"
  "}"
  "QTreeWidget{"
  " background-color: rgb( " PALETTE_BACKGROUND_COLOR ") ;"
  " alternate-background-color: rgb( " ALTERNATE_BACKGROUND_COLOR ") ;"
  " selection-background-color: rgb( " SELECT_COLOR ") ;"
  " border: none;"
  " color: rgb( " FONT_COLOR ") ;"
  " selection-color: rgb( " FONT_COLOR ") ;"
  "}"
  "QTreeWidget::indicator {"
  " width: 13px;"
  " height: 13px;"
  "}"
  "QTreeWidget::indicator:unchecked {"
  " image: url(:/General_Icons/checkbox-unselected.png);"
  "}"
  "QTreeWidget::indicator:checked {"
  " image: url(:/General_Icons/checkbox-selected.png);"
  "}"
  "QTreeWidget::indicator:indeterminate {"
  " image: url(:/General_Icons/checkbox-indeterminate.png);"
  "}"
  "QTreeWidget::branch:has-children:!has-siblings:closed,"
  "QTreeWidget::branch:closed:has-children:has-siblings {"
  " padding-left: 4px;"
  " image: url(:/General_Icons/arrow-expand.png);"
  "}"
  "QTreeWidget::branch:open:has-children:!has-siblings,"
  "QTreeWidget::branch:open:has-children:has-siblings  {"
  " padding-left: 4px;"
  " image: url(:/General_Icons/arrow-expanded.png);"
  "}"
  "QTreeView{"
  " background-color: rgb( " PALETTE_BACKGROUND_COLOR ") ;"
  " alternate-background-color: rgb( " ALTERNATE_BACKGROUND_COLOR ") ;"
  " selection-background-color: rgb( " SELECT_COLOR ") ;"
  " border: none;"
  " color: rgb( " FONT_COLOR ") ;"
  " selection-color: rgb( " FONT_COLOR ") ;"
  " outline: none;"
  "}"
  "QTreeView::item:selected{"
  " background-color: rgb( " SELECT_COLOR ") ;"
  "}"
  "QTreeView::branch:selected{"
  " background-color: rgb( " SELECT_COLOR ") ;"
  "}"
  "QTreeView::branch:has-children:!has-siblings:closed,"
  "QTreeView::branch:closed:has-children:has-siblings {"
  " padding-left: 4px;"
  " image: url(:/General_Icons/arrow-expand.png);"
  "}"
  "QTreeView::branch:open:has-children:!has-siblings,"
  "QTreeView::branch:open:has-children:has-siblings  {"
  " padding-left: 4px;"
  " image: url(:/General_Icons/arrow-expanded.png);"
  "}"
  "QPlainTextEdit{"
   " background-color: rgb( " LARGE_FORM_BACKGROUND_COLOR ") ;"
   " color: rgb( " LARGE_FORM_FONT_COLOR ") ;"
   " selection-background-color: rgb( " ACCENT_COLOR ") ; "
   " selection-color: rgb( " FONT_COLOR ") ; "
   "}"
  "QTextEdit{"
   " background-color: rgb( " LARGE_FORM_BACKGROUND_COLOR ") ;"
   " color: rgb( " LARGE_FORM_FONT_COLOR ") ;"
   " selection-background-color: rgb( " ACCENT_COLOR ") ; "
   " selection-color: rgb( " FONT_COLOR ") ; "
   "}"
  "QTextBrowser{"
   " background-color: rgb( " LARGE_FORM_BACKGROUND_COLOR ") ;"
   " color: rgb( " LARGE_FORM_FONT_COLOR ") ;"
   " selection-background-color: rgb( " ACCENT_COLOR ") ; "
   " selection-color: rgb( " FONT_COLOR ") ; "
   "}"
  "QLineEdit{"
  " text-align: left;"
  " color: rgb( " FONT_COLOR ") ;"
  " background-color: rgb( " FORM_BACKGROUND_COLOR ") ;"
  " selection-background-color: rgb( " ACCENT_COLOR ") ; "
  " selection-color: rgb( " FONT_COLOR ") ; "
  " border-radius: 3px;"
  " padding: 0px;"
  " margin: 0px;"
   //" margin: 1px;"
  "}"
  ".QDoubleSpinBox{"
  " background-color: rgb( " SELECT_COLOR ") ;"
  " color: rgb( " FONT_COLOR ") ;"
  " selection-background-color: rgb( " ACCENT_COLOR ") ; "
  " selection-color: rgb( " FONT_COLOR ") ; "
  " border: 1px insetrgb( " BORDER_COLOR ") ;"
  " border-radius: 3px;"
  " background-origin: margin;"
  " background-position: top center;"
  " margin-right: 15px;"
  " margin-left: 0px;"
  " margin-top: 0px;"
  " margin-bottom: 0px;"
  " padding-left: 2px;"
  " min-height: 20px;"
  "}"
  ".QDoubleSpinBox:disabled{"
  " background-color: rgb( " HOVER_COLOR ") ;"
  " color: gray ;"
  "}"
  "QDoubleSpinBox::up-button {"
  " background-color: transparent;"
  " image: url(:/General_Icons/arrow-up.png);"
  " border-top: 3px transparent;"
  " border-bottom: 3px transparent;"
  " border-right: 1px transparent;"
  " border-left: 1px transparent;"
  " subcontrol-position: right top;"
  " subcontrol-origin: margin;"
  " margin-top:2px;"
  " margin-bottom:6px;"
  " height: 5px;"
  "}"
  "QDoubleSpinBox::down-button {"
  " background-color: transparent;"
  " image: url(:/General_Icons/arrow-down.png);"
  " border-top: 3px transparent;"
  " border-bottom: 3px transparent;"
  " border-right: 1px transparent;"
  " border-left: 1px transparent;"
  " subcontrol-position: right bottom;"
  " subcontrol-origin: margin;"
  " margin-top:6px;"
  " margin-bottom:2px;"
  " height: 5px;"
  "}"
  "QWidget#sliderDoubleBase_ .QDoubleSpinBox{"
  " background-color: rgb( " SELECT_COLOR ") ;"
  " color: rgb( " FONT_COLOR ") ;"
  " selection-background-color: rgb( " ACCENT_COLOR ") ; "
  " selection-color: rgb( " FONT_COLOR ") ; "
  " border: 1px insetrgb( " BORDER_COLOR ") ;"
  " border-radius: 3px;"
  " background-origin: margin;"
  " background-position: top center;"
  " margin-right: 15px;"
  " margin-left: 5px;"
  " margin-top: 5px;"
  " margin-bottom: 20px;"
  " padding-left: 2px;"
  "}"
  "QWidget#sliderDoubleBase_ QDoubleSpinBox::up-button {"
  " background-color: transparent;"
  " image: url(:/General_Icons/arrow-up.png);"
  " border-top: 3px transparent;"
  " border-bottom: 3px transparent;"
  " border-right: 1px transparent;"
  " border-left: 1px transparent;"
  " subcontrol-position: right top;"
  " subcontrol-origin: margin;"
  " margin-top:6px;"
  " margin-bottom:6px;"
  "}"
  "QWidget#sliderDoubleBase_ QDoubleSpinBox::down-button {"
  " background-color: transparent;"
  " image: url(:/General_Icons/arrow-down.png);"
  " border-top: 3px transparent;"
  " border-bottom: 1px transparent;"
  " border-right: 3px transparent;"
  " border-left: 1px transparent;"
  " subcontrol-position: right center;"
  " subcontrol-origin: margin;"
  " margin-top:4px;"
  " margin-bottom:8px;"
  "}"
  ".QSpinBox{"
  " background-color: rgb( " SELECT_COLOR ") ;"
  " color: rgb( " FONT_COLOR ") ;"
  " selection-background-color: rgb( " ACCENT_COLOR ") ; "
  " selection-color: rgb( " FONT_COLOR ") ; "
  " border: 1px insetrgb( " BORDER_COLOR ") ;"
  " border-radius: 3px;"
  " background-origin: margin;"
  " background-position: top center;"
  " margin-right: 15px;"
  " margin-left: 0px;"
  " margin-top: 0px;"
  " margin-bottom: 0px;"
  " padding-left: 2px;"
  " min-height: 20px;"
  "}"
  ".QSpinBox:disabled{"
  " background-color: rgb( " HOVER_COLOR ") ;"
  " color: gray ;"
  "}"
  "QSpinBox::up-button {"
  " background-color: transparent;"
  " image: url(:/General_Icons/arrow-up.png);"
  " border-top: 3px transparent;"
  " border-bottom: 3px transparent;"
  " border-right: 1px transparent;"
  " border-left: 1px transparent;"
  " subcontrol-position: right top;"
  " subcontrol-origin: margin;"
  " margin-top:2px;"
  " margin-bottom:6px;"
  " height: 5px;"
  "}"
  "QSpinBox::down-button {"
  " background-color: transparent;"
  " image: url(:/General_Icons/arrow-down.png);"
  " border-top: 3px transparent;"
  " border-bottom: 3px transparent;"
  " border-right: 1px transparent;"
  " border-left: 1px transparent;"
  " subcontrol-position: right bottom;"
  " subcontrol-origin: margin;"
  " margin-top:6px;"
  " margin-bottom:2px;"
  " height: 5px;"
  "}"
  "QWidget#sliderIntBase_ .QSpinBox{"
  " background-color: rgb( " SELECT_COLOR ") ;"
  " color: rgb( " FONT_COLOR ") ;"
  " selection-background-color: rgb( " ACCENT_COLOR ") ; "
  " selection-color: rgb( " FONT_COLOR ") ; "
  " border: 1px insetrgb( " BORDER_COLOR ") ;"
  " border-radius: 3px;"
  " background-origin: margin;"
  " background-position: top center;"
  " margin-right: 15px;"
  " margin-left: 5px;"
  " margin-top: 5px;"
  " margin-bottom: 20px;"
  " padding-left: 2px;"
 "}"
  "QWidget#sliderIntBase_ QSpinBox::up-button {"
  " background-color: transparent;"
  " image: url(:/General_Icons/arrow-up.png);"
  " border-top: 3px transparent;"
  " border-bottom: 3px transparent;"
  " border-right: 2px transparent;"
  " border-left: 2px transparent;"
  " subcontrol-position: right top;"
  " subcontrol-origin: margin;"
  " margin-top:6px;"
  " margin-bottom:6px;"
  "}"
  "QWidget#sliderIntBase_ QSpinBox::down-button {"
  " background-color: transparent;"
  " image: url(:/General_Icons/arrow-down.png);"
  " border-top: 3px transparent;"
  " border-bottom: 3px transparent;"
  " border-right: 2px transparent;"
  " border-left: 2px transparent;"
  " subcontrol-position: right center;"
  " subcontrol-origin: margin;"
  " margin-top:4px;"
  " margin-bottom:8px;"
  "}"
  "QProgressBar {"
  " background-color: rgb(" PALETTE_BACKGROUND_COLOR ");"
   //" border: 2px solid rgb(" BORDER_COLOR ");"
  " border-radius: 3px;"
  " text-align: center;"
  " color: rgb(" FONT_COLOR ");"
   "}"
  "QProgressBar::chunk {"
  " background-color: rgb(" ACCENT_COLOR ");"
  "}"
  "QPushButton{"
  " background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
  "   stop:0 rgba(100, 99, 106, 255), "
  "   stop:0.45 rgba(81,80,87,255), "
  "   stop:0.6 rgba(22, 22, 22, 255), "
  "   stop:0.76 rgba(38, 38, 40, 255));"
  " color: rgb( " FONT_COLOR ") ;"
  " border-radius: 3px;"
  " border: 1px ridge rgba(106, 106, 112, 255);"
  " margin:4px;"
  " padding: 4px 6px 4px 6px;"
  "}"
  "QPushButton:disabled{"
  " background-color: rgb( " HOVER_COLOR ") ;"
  " color: gray;"
  "}"
  "QPushButton:hover{"
  " background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
  "   stop:0 rgba(98, 97, 103, 255), "
  "   stop:0.253769 rgba(11, 11, 11, 255), "
  "   stop:1 rgba(24, 24, 26, 255));"
  "}"
  "QPushButton:pressed{"
  " background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
  "   stop:0 rgba(10, 10, 12, 255), "
  "   stop:0.753769 rgba(81,80,87, 255), "
  "   stop:1 rgba(96, 95, 100, 255));"
  " border: 1px inset rgba(106, 106, 112, 255);"
  "}"
  "QWidget#background_{"
  " background-color: rgb( " PALETTE_BACKGROUND_COLOR ") ;"
  " color: rgb( " FONT_COLOR ") ; "
  " border-style: none;"
  " border-radius: 3px;"
  " margin: 0px;"
  "}"
  "QWidget#histogram_{"
  " background-color: rgb( " LARGE_FORM_BACKGROUND_COLOR ") ;"
  " color: rgb( " LARGE_FORM_FONT_COLOR ") ;"
  " border-style: none;"
  " border-radius: 0px;"
  " margin: 0px;"
  "}"
  "QToolButton{"
  " background-color: rgba(0, 0, 0, 0);"
  " border: 2px solid rgba(0, 0, 0, 0);"
  " border-radius: 2px;"
  " margin: 0 0 0 0;"
  " padding: 0 0 0 0;"
  "}"
  "QToolButton:hover{"
  " background-color: rgb( " HOVER_COLOR ") ;"
  "}"
  "QToolButton:checked:!hover{"
  " background-color: rgb( " SELECT_COLOR ") ;"
  " margin: 0 0 0 0;"
  " padding: 0 0 0 0;"
  "}"
  "QGroupBox{"
  " color: rgb( " FONT_COLOR ") ;"
  " font: normal;"
  " font-size: 10px;"
  "}"
  "QGroupBox::indicator {"
  " width: 13px;"
  " height: 13px;"
  "}"
  "QGroupBox::indicator:unchecked {"
  " image: url(:/General_Icons/checkbox-unselected.png);"
  "}"
  "QGroupBox::indicator:checked {"
  " image: url(:/General_Icons/checkbox-selected.png);"
  "}"
  "QComboBox{"
  " background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
  "   stop:0 rgba(100, 99, 106, 255), "
  "   stop:0.45 rgba(81,80,87,255), "
  "   stop:0.6 rgba(22, 22, 22, 255), "
  "   stop:0.76 rgba(38, 38, 40, 255));"
  " border-radius: 3px;"
  " border: 1px ridge rgba(106, 106, 112, 255);"
  " color: rgb( " FONT_COLOR ") ;"
  " margin: 0px;"
  " padding: 0px 6px 0px 6px;"
  " selection-background-color: rgb( " SELECT_COLOR ") ; "
  " selection-color: rgb( " FONT_COLOR ") ; "
  "}"
  "QComboBox QAbstractItemView{"
  " background-color:rgb( " PALETTE_BACKGROUND_COLOR ") ;"
  " color: rgb( " FONT_COLOR ") ;"
  " padding: -2px -2px -2px -2px;"
  " margin: 1px 1px 1px 1px;"
  "}"
  "QComboBox QAbstractItemView::item{"
  " selection-background-color: rgb( " SELECT_COLOR ") ; "
  " selection-color: rgb( " FONT_COLOR ") ; "
  "}"
  "QComboBox:disabled{"
  " background-color: rgb( " HOVER_COLOR ") ;"
  " color: gray;"
  "}"
  "QComboBox:off{"
  " background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
  "   stop:0 rgba(100, 99, 106, 255), "
  "   stop:0.45 rgba(81,80,87,255), "
  "   stop:0.6 rgba(22, 22, 22, 255), "
  "   stop:0.76 rgba(38, 38, 40, 255));"
  " border-radius: 3px;"
  " border: 1px ridge rgba(106, 106, 112, 255);"
  " color: rgb( " FONT_COLOR ") ;"
  " margin: 0px;"
  " padding: 0px 6px 0px 6px;"
  "}"
  "QComboBox::drop-down{"
  " subcontrol-origin: padding; "
  " subcontrol-position: top right; "
  " border-top-right-radius: 3px; "
  " border-bottom-right-radius: 3px; "
  " border-color: rgba(0,0,0,0);"
  " background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
  "   stop:0 rgba(110, 109, 116, 255), "
  "   stop:0.45 rgba(91,90,97,255), "
  "   stop:0.6 rgba(32, 32, 32, 255), "
  "   stop:0.76 rgba(48, 48, 50, 255));"
  "}"
  "QComboBox:!editable:unchecked, QComboBox:on{"
  " background-color: rgb( " SELECT_COLOR ") ;"
  " color: rgb( " FONT_COLOR ") ;"
  " border-style: none;"
  "}"
  "QComboBox:!editable:checked:hover{"
  " background-color: rgb( " SELECT_COLOR ") ;"
  " color: rgb( " FONT_COLOR ") ;"
  " border: none;"
  " border-radius: 0px;"
  "}"
  "QComboBox:checked:!hover{"
  " background-color:rgb( " SELECT_COLOR ") ;"
  "}"
  "QComboBox::down-arrow{"
  " border-color: rgba(0,0,0,0);"
  " image: url(:/General_Icons/arrow-down.png);"
  "}"
  "QComboBox::down-arrow:on{"
  " top: 1px;"
  " left: 1px;"
  "}"
  "QComboBox::drop-down:disabled{"
  " background-color: rgb( " HOVER_COLOR ") ;"
  " color: gray;"
  "}"
   "QComboBox:hover{"
  " border: 1px solid rgb(" SELECT_COLOR ");"
  "}"
   "QCheckBox {"
   " color: rgb( " FONT_COLOR ") ;"
   " spacing: 5px;"
   " margin: 4px;"
   "}"
   "QCheckBox:disabled {"
   " color: gray ;"
   "}"
   "QCheckBox::indicator {"
   " width: 13px;"
   " height: 13px;"
   "}"
   "QCheckBox::indicator:unchecked {"
   " image: url(:/General_Icons/checkbox-unselected.png);"
   "}"
   "QCheckBox::indicator:checked {"
   " image: url(:/General_Icons/checkbox-selected.png);"
   "}"
   "QRadioButton {"
   " color: rgb( " FONT_COLOR ") ;"
   " spacing: 5px;"
   " margin: 4px;"
   "}"
   "QRadioButton::indicator {"
   " width: 13px;"
   " height: 13px;"
   "}"
   "QRadioButton::indicator:unchecked {"
   " image: url(:/General_Icons/radio-empty.png);"
   "}"
   "QRadioButton::indicator:checked {"
   " image: url(:/General_Icons/radio-fill.png);"
   "}"
    ); // end MAIN_STYLE_C

// === GroupMenuBar === //
const QString StyleSheet::GROUP_MENUBAR_C = QString::fromUtf8(
  "QWidget#group_tools_{"
  " border-radius: 3px;"
  " border: 3px solid rgb( " BORDER_COLOR ") ;"
  " background-color: rgb( 106, 106, 112 );"
  " color: white;"
  " border-top-width: 0px;"
  " border-top-right-radius: 0px;"
  " border-top-left-radius: 0px;"
  "}"
  "QWidget#iso_quality_{"
  " border-top: 1px solid rgb( " HOVER_COLOR ") ;"
  " margin-left: 3px;"
  " margin-right: 3px;"
  "}"
  "QWidget#duplicate_layers_{"
  " border-top: 1px solid rgb( " HOVER_COLOR ") ;"
  " margin-left: 3px;"
  " margin-right: 3px;"
  "}"
  "QWidget#delete_{"
  " border-top: 1px solid rgb( " HOVER_COLOR ") ;"
  " margin-left: 3px;"
  " margin-right: 3px;"
  "}"
  );
// === StatusBar === //
const QString StyleSheet::STATUSBAR_C = QString::fromUtf8(
  "QStatusBar::item {"
  " border-style: none; }"
  "QToolButton:checked:!hover {"
  " background-color: rgb( " FOOTER_COLOR ") ;"
  " border-radius: 6px;"
  " margin: 0 0 0 0;"
  " padding: 0 0 0 0;"
  "}"
  ".QWidget {"
  " background-color: rgb( " SELECT_COLOR ") ;"
  "}"
  "QLabel {"
  " background-color: rgb( " SELECT_COLOR ") ;"
  "}"
  "QWidget#label_values_ QWidget {"
  " background-color: rgb( " FOOTER_COLOR ") ;"
  "}"
  "QWidget#label_values_ QLabel {"
  " background-color: rgb( " FOOTER_COLOR ") ;"
  "}"
  // invert tool buttons since label_values_
  // have such a dark background
  "QWidget#label_values_ QToolButton:hover {"
  " background-color: rgb( " SELECT_COLOR ") ;"
  " border-radius: 3px;"
 "}"
  "QWidget#label_values_ QToolButton:checked:!hover {"
  " background-color: rgb( " HOVER_COLOR ") ;"
  " border-radius: 6px;"
  " margin: 0 0 0 0;"
  " padding: 0 0 0 0;"
 "}"
    );

const QString StyleSheet::STATUSBAR_ERROR_C = QString::fromUtf8(
  "QLabel#status_report_label_{"
  " color: rgb(" ERROR_COLOR ");"
  " font: bold;"
  "}" );

const QString StyleSheet::STATUSBAR_WARNING_C = QString::fromUtf8(
  "QLabel#status_report_label_{"
  " color: rgb(" WARNING_COLOR ");"
  " font: bold;"
  "}" );
  
const QString StyleSheet::STATUSBAR_MESSAGE_C = QString::fromUtf8(
  "QLabel#status_report_label_{"
  " color: rgb(" MESSAGE_COLOR ");"
  " font: bold;"
  "}" );
const QString StyleSheet::STATUSBAR_DEBUG_C = QString::fromUtf8(
  "QLabel#status_report_label_{"
  " color: " DEBUG_COLOR ";"
  " font: bold;"
  "}" );
  
// === ToolBoxWidget Styles === //
const QString StyleSheet::TOOLBOXWIDGET_C = QString( 
  "QWidget#tool_main_ {"
  " background-color: rgb( " BACKGROUND_COLOR ") ;"
  " border-radius: 0px;"
  " border: none;"
  "}"
  "QFrame#tool_frame_{"
  " background-color: rgb( " PALETTE_BACKGROUND_COLOR ") ;"
  " border: 3px solid rgb( " BORDER_COLOR ") ; "
  " border-top-width: 0px;"
  " border-radius: 3px;"
  " border-top-right-radius: 0px;"
  " border-top-left-radius: 0px;"
  "}"
  "QToolButton#help_button_{"
  " background-color: rgba(0, 0, 0, 0);"
  " border-radius: 1px;"
  " border-width: 1px;"
 "}"
  "QToolButton#close_button_{"
  " background-color: rgba(0, 0, 0, 0);"
  " border-radius: 1px;"
  " border-width: 1px;"
 "}"
  "QToolButton#help_button_:checked:!hover {"
  " background-color: rgba(0, 0, 0, 0);"
  " border: 1px solid rgba(0, 0, 0, 0);"
  " margin: 0 0 0 0;"
  " padding: 0 0 0 0;"
 "}"
  "QToolButton#help_button_:!hover {"
  " background-color: rgba(0, 0, 0, 0);"
  " border: 1px solid rgba(0, 0, 0, 0);"
  " margin: 0 0 0 0;"
  " padding: 0 0 0 0;"
 "}"
  "QToolButton#spacer_{"
  " background-color: rgba(0, 0, 0, 0);"
  " margin-right: 7px;"
  " height: 24px;"
  " padding-left: 4px;"
  " border-style: none;"
  "}"
  "QToolButton#spacer_:hover{"
  " background-color: rgba(0, 0, 0, 0);"
  " color: rgb( " FONT_COLOR ") ;"
  " margin-right: 7px;"
  " height: 24px;"
  " padding-left: 4px;"
  " border-style: none;"
  "}"
  "QToolButton#spacer_:pressed{"
  " background-color: rgba(0, 0, 0, 0);"
  " color: rgb( " FONT_COLOR ") ;"
  " margin-right: 7px;"
  " height: 24px;"
  " padding-left: 4px;"
  " border-style: none;"
  "}"
 );
  
// === ToolBoxPageWidget Styles === //
// - page_background_ - //
const QString StyleSheet::TOOLBOXPAGEWIDGET_PAGE_BACKGROUND_ACTIVE_C = QString( 
  "QWidget#page_background_ {"
  " background-color: rgb( " ACCENT_COLOR ") ;"
  " border-radius: 3px;"
  " border: 3px solid rgb( " BORDER_COLOR ") ;"
  " border-bottom-width: 0px;"
  " border-bottom-right-radius: 0px;"
  " border-bottom-left-radius: 0px;"
  "}"
  "QWidget#page_header_ {"
  " padding-right: 3px; "
  "}"
  );
const QString StyleSheet::TOOLBOXPAGEWIDGET_PAGE_BACKGROUND_INACTIVE_C = QString( 
  "QWidget#page_background_ {"
  " background-color: rgb( " INACTIVE_COLOR ") ;"
  " border-radius: 3px;"
  " border: 2px solid rgb( " BORDER_COLOR ") ;"
"}"
  "QWidget#page_header_ {"
  " padding-right: 3px; "
  "}"
  );
  
// - activate_button_ - //
const QString StyleSheet::TOOLBOXPAGEWIDGET_ACTIVATE_BUTTON_ACTIVE_C = QString( 
  "QToolButton#activate_button_{"
  " background-color: rgba(0, 0, 0, 0);"
  " text-align: left;"
  " margin-right: 7px;"
  " height: 24px;"
  " padding-left: 4px;"
  " border-style: none;"
  " color: rgb( " FONT_COLOR ") ;"
  " font: bold;"
#ifdef __APPLE__
  "   font-size: 13;"
#endif  
  "}"
  "QToolButton#activate_button_:hover{"
  " background-color: rgba(0, 0, 0, 0);"
  " color: rgb( " HOVER_COLOR ") ;"
  " text-align: left;"
  " margin-right: 7px;"
  " height: 24px;"
  " padding-left: 4px;"
  " border-style: none;"
  "}"
  "QToolButton#activate_button_:pressed{"
  " background-color: rgba(0, 0, 0, 0);"
  " color: rgb( " SELECT_COLOR ") ;"
  " text-align: left;"
  " margin-right: 7px;"
  " height: 24px;"
  " padding-left: 4px;"
  " border-style: none;"
  "}"
  );
  
const QString StyleSheet::TOOLBOXPAGEWIDGET_ACTIVATE_BUTTON_INACTIVE_C = QString( 
  "QToolButton#activate_button_{"
  " background-color: rgba(0, 0, 0, 0);"
  " margin-right: 7px;"
  " height: 24px;"
  " text-align: left;"
  " padding-left: 4px;"
  " border: none;"
  " color: rgb( " FONT_COLOR ") ;"
  " font: normal;"
#ifdef __APPLE__
  "   font-size: 13;"
#endif  
  "}\n"
  "QToolButton#activate_button_:hover{"
  " background-color: rgba(0, 0, 0, 0);"
  " color: rgb( " PALETTE_BACKGROUND_COLOR ") ;"
  " margin-right: 7px;"
  " height: 24px;"
  " text-align: left;"
  " padding-left: 4px;"
  " border: none;"
  "}"
  "QToolButton#activate_button_:pressed{"
  " background-color: rgba(0, 0, 0, 0);"
  " color: rgb( " SELECT_COLOR ") ;"
  " margin-right: 7px;"
  " height: 24px;"
  " text-align: left;"
  " padding-left: 4px;"
  " border: none;"
  "}"
  "QToolButton#spacer_{"
  " background-color: rgba(0, 0, 0, 0);"
  " margin-right: 7px;"
  " height: 24px;"
  " padding-left: 4px;"
  " border: none;"
  " color: rgb(25, 25, 25);"
  "}"
  "QToolButton#spacer_:hover{"
  " background-color: rgba(0, 0, 0, 0);"
  " margin-right: 7px;"
  " height: 24px;"
  " padding-left: 4px;"
  " border: none;"
  " color: silver;"
  "}"
  "QToolButton#spacer_:pressed{"
  " background-color: rgba(0, 0, 0, 0);"
  " margin-right: 7px;"
  " height: 24px;"
  " padding-left: 4px;"
  " border: none;"
  " color: rgb(68, 68, 68);"
  "}"
  );

const QString StyleSheet::RENDERINGWIDGET_C = QString(
  "QWidget#scrollAreaWidgetContents{"
  " background-color: rgb( " BACKGROUND_COLOR ") ;"
  " border: none;"
  " border-radius: 0px;"
  "}"
  "QWidget#clipping_content_{"
  " border: 3px solid rgb( " BORDER_COLOR ") ;"
  " border-radius: 3px;"
  " border-top-width: 0px;"
  " border-top-right-radius: 0px;"
  " border-top-left-radius: 0px;"
  " background-color: rgb( " PALETTE_BACKGROUND_COLOR ") ;"
  "}"
  "QWidget#vr_content_{"
  " border: 3px solid rgb( " BORDER_COLOR ") ;"
  " border-radius: 3px;"
  " border-top-width: 0px;"
  " border-top-right-radius: 0px;"
  " border-top-left-radius: 0px;"
  " background-color: rgb( " PALETTE_BACKGROUND_COLOR ") ;"
  "}"
  "QWidget#fog_content_{"
  " border: 3px solid rgb( " BORDER_COLOR ") ;"
  " border-radius: 3px;"
  " border-top-width: 0px;"
  " border-top-right-radius: 0px;"
  " border-top-left-radius: 0px;"
  " background-color: rgb( " PALETTE_BACKGROUND_COLOR ") ;"
  "}"
  );
const QString StyleSheet::RENDERING_CLIPPING_ACTIVE_C = QString( 
  "QWidget#clipping_header_bkg_ {"
  " background-color:rgb( " ACCENT_COLOR ") ;"
  " border-radius: 3px;"
  " border: 3px solid rgb( " BORDER_COLOR ") ;"
  " border-bottom-width: 0px;"
  " border-bottom-right-radius: 0px;"
  " border-bottom-left-radius: 0px;"
  "}"
  "QToolButton#clipping_open_button_{"
  " margin-right: 7px;"
  " height: 24px;"
  " text-align: left;"
  " border: none;"
  " background-color: transparent;"
  " color: rgb( " FONT_COLOR ") ;"
  " font: bold;"
#ifdef __APPLE__
  "   font-size: 13;"
#endif  
  "}"
  "QToolButton#clipping_open_button_:hover{"
  " color: rgb( " HOVER_COLOR ") ;"
  " background-color: transparent;"
  "}"
  "QToolButton#clipping_open_button_:pressed{"
  " padding-left: 4px;"
  " border: none;"
  " color: rgb( " SELECT_COLOR ") ;"
  " background-color: transparent;"
  "}"
  "QToolButton#clipping_spacer_{"
  " margin-right: 7px;"
  " height: 24px;"
  " padding-left: 4px;"
  " border: none;"
  " background-color: transparent;"
  "}"
  "QToolButton#clipping_spacer_:hover{"
  " color: rgb( " FONT_COLOR ") ;"
   " background-color: transparent;"
 "}"
  "QToolButton#clipping_spacer_:pressed{"
  " padding-left: 4px;"
  " border: none;"
  " color: rgb( " FONT_COLOR ") ;"
  " background-color: transparent;"
  "}"
  );
  
const QString StyleSheet::RENDERING_CLIPPING_INACTIVE_C = QString( 
  "QWidget#clipping_header_bkg_ {"
  " background-color:  rgb( " INACTIVE_COLOR ") ;"
  " border-radius: 3px;"
  " border: 2px solid rgb( " BORDER_COLOR ") ;"
  "}"
  "QToolButton#clipping_open_button_{"
  " margin-right: 7px;"
  " height: 24px;"
  " text-align: left;"
  " padding-left: 4px;"
  " border: none;"
  " color: rgb( " FONT_COLOR ") ;"
  " background-color: transparent;"
  " font: normal;"
#ifdef __APPLE__
  "   font-size: 13;"
#endif  
  "}"
  "QToolButton#clipping_open_button_:hover{"
  " color: rgb( " PALETTE_BACKGROUND_COLOR ") ;"
  " background-color: transparent;"
  "}"
  "QToolButton#clipping_open_button_:pressed{"
  " padding-left: 4px;"
  " border: none;"
  " color: rgb( " SELECT_COLOR ") ;"
  " background-color: transparent;"
  "}"
  "QToolButton#clipping_spacer_{"
  " margin-right: 7px;"
  " height: 24px;"
  " text-align: left;"
  " padding-left: 4px;"
  " border: none;"
  " color: rgb(25, 25, 25);"
  " background-color: transparent;"
  " font: normal;"
#ifdef __APPLE__
  "   font-size: 13;"
#endif  
  "}"
  "QToolButton#clipping_spacer_:hover{"
  " color: silver;"
  " background-color: transparent;"
  "}"
  "QToolButton#clipping_spacer_:pressed{"
  " padding-left: 4px;"
  " border: none;"
  " color: rgb(68, 68, 68);"
  " background-color: transparent;"
  "}"

  );


const QString StyleSheet::RENDERING_VR_ACTIVE_C = QString( 
  "QWidget#vr_header_bkg_ {"
  " background-color:rgb( " ACCENT_COLOR ") ;"
  " border-radius: 3px;"
  " border: 3px solid rgb( " BORDER_COLOR ") ;"
  " border-bottom-width: 0px;"
  " border-bottom-right-radius: 0px;"
  " border-bottom-left-radius: 0px;"
  "}"
  "QToolButton#vr_open_button_{"
  " margin-right: 7px;"
  " height: 24px;"
  " text-align: left;"
  " padding-left: 4px;"
  " border: none;"
  " background-color: transparent;"
  " color: rgb( " FONT_COLOR ") ;"
  " font: bold;"
#ifdef __APPLE__
  "   font-size: 13;"
#endif  
  "}"
  "QToolButton#vr_open_button_:hover{"
  " background-color: transparent;"
  " color: rgb( " HOVER_COLOR ") ;"
  "}"
  "QToolButton#vr_open_button_:pressed{"
  " padding-left: 4px;"
  " border: none;"
  " background-color: transparent;"
  " color: rgb( " SELECT_COLOR ") ;"
  "}"

  "QToolButton#vr_spacer_{"
  " margin-right: 7px;"
  " height: 24px;"
  " padding-left: 4px;"
  " border: none;"
  " background-color: transparent;"
  " color: rgb( " FONT_COLOR ") ;"
  "}"
  "QToolButton#vr_spacer_:hover{"
  " background-color: transparent;"
  " color: rgb( " FONT_COLOR ") ;"
  "}"
  "QToolButton#vr_spacer_:pressed{"
  " padding-left: 4px;"
  " border: none;"
  " background-color: transparent;"
  " color: rgb( " FONT_COLOR ") ;"
  "}"
  );
  
const QString StyleSheet::RENDERING_VR_INACTIVE_C = QString( 
  "QWidget#vr_header_bkg_ {"
  " background-color:  rgb( " INACTIVE_COLOR ") ;"
  " border-radius: 3px;"
  " border: 2px solid rgb( " BORDER_COLOR ") ;"
  "}"
  "QToolButton#vr_open_button_{"
  " margin-right: 7px;"
  " height: 24px;"
  " text-align: left;"
  " padding-left: 4px;"
  " border: none;"
  " color: rgb( " FONT_COLOR ") ;"
  " background-color: transparent;"
  " font: normal;"
#ifdef __APPLE__
  "   font-size: 13;"
#endif  
  "}"
  "QToolButton#vr_open_button_:hover{"
  " color: rgb( " PALETTE_BACKGROUND_COLOR ") ;"
  " background-color: transparent;"
  "}"
  "QToolButton#vr_open_button_:pressed{"
  " padding-left: 4px;"
  " border: none;"
  " color: rgb( " SELECT_COLOR ") ;"
  " background-color: transparent;"
  "}"
  "QToolButton#vr_spacer_{"
  " margin-right: 7px;"
  " height: 24px;"
  " text-align: left;"
  " border: none;"
  " color: rgb(25, 25, 25);"
  " background-color: transparent;"
  "}"
  "QToolButton#vr_spacer_:hover{"
  " color: silver;"
  " background-color: transparent;"
  "}"
  "QToolButton#vr_spacer_:pressed{"
  " padding-left: 4px;"
  " border: none;"
  " color: rgb(68, 68, 68);"
  " background-color: transparent;"
  "}"
  );

const QString StyleSheet::RENDERING_FOG_ACTIVE_C = QString( 
  "QWidget#fog_header_bkg_ {"
  " background-color:rgb( " ACCENT_COLOR ") ;"
  " border-radius: 3px;"
  " border: 3px solid rgb( " BORDER_COLOR ") ;"
  " border-bottom-width: 0px;"
  " border-bottom-right-radius: 0px;"
  " border-bottom-left-radius: 0px;"
  "}"
  "QToolButton#fog_open_button_{"
  " margin-right: 7px;"
  " height: 24px;"
  " text-align: left;"
  " padding-left: 4px;"
  " border: none;"
  " background-color: transparent;"
  " color: rgb( " FONT_COLOR ") ;"
  " font: bold;"
#ifdef __APPLE__
  "   font-size: 13;"
#endif  
  "}"
  "QToolButton#fog_open_button_:hover{"
  " background-color: transparent;"
  " color: rgb( " HOVER_COLOR ") ;"
  "}"
  "QToolButton#fog_open_button_:pressed{"
  " padding-left: 4px;"
  " border: none;"
  " background-color: transparent;"
  " color: rgb( " SELECT_COLOR ") ;"
  "}"
  "QToolButton#fog_spacer_{"
  " margin-right: 7px;"
  " height: 24px;"
  " padding-left: 4px;"
  " border: none;"
  " background-color: transparent;"
  " color: rgb( " FONT_COLOR ") ;"
  "}"
  "QToolButton#fog_spacer_:hover{"
  " background-color: transparent;"
  " color: rgb( " FONT_COLOR ") ;"
  "}"
  "QToolButton#fog_spacer_:pressed{"
  " padding-left: 4px;"
  " border: none;"
  " background-color: transparent;"
  " color: rgb( " FONT_COLOR ") ;"
  "}"
  );
  
const QString StyleSheet::RENDERING_FOG_INACTIVE_C = QString( 
  "QWidget#fog_header_bkg_ {"
  " background-color:  rgb( " INACTIVE_COLOR ") ;"
  " border-radius: 3px;"
  " border: 2px solid rgb( " BORDER_COLOR ") ;"
  "}"
  "QToolButton#fog_open_button_{"
  " margin-right: 7px;"
  " height: 24px;"
  " text-align: left;"
  " padding-left: 4px;"
  " border: none;"
  " color: rgb( " FONT_COLOR ") ;"
  " background-color: transparent;"
  " font: normal;"
#ifdef __APPLE__
  "   font-size: 13;"
#endif  
  "}"
  "QToolButton#fog_open_button_:hover{"
  " color: rgb( " PALETTE_BACKGROUND_COLOR ") ;"
  " background-color: transparent;"
  "}"
  "QToolButton#fog_open_button_:pressed{"
  " padding-left: 4px;"
  " border: none;"
  " color: rgb( " SELECT_COLOR ") ;"
  " background-color: transparent;"
  "}"
  "QToolButton#fog_spacer_{"
  " margin-right: 7px;"
  " height: 24px;"
  " padding-left: 4px;"
  " border: none;"
  " background-color: transparent;"
  "}"
  "QToolButton#fog_spacer_:hover{"
  " color: silver;"
  " background-color: transparent;"
  "}"
  "QToolButton#fog_spacer_:pressed{"
  " padding-left: 4px;"
  " border: none;"
  " color: rgb(68, 68, 68);"
  " background-color: transparent;"
  "}"
  );

// === ProjectDockWidget Styles === //
  const QString StyleSheet::PROJECTDOCKWIDGET_C = QString(
     "QWidget#dockWidgetContents QGroupBox{"
    " background-color: rgb( " PALETTE_BACKGROUND_COLOR ") ;"
    "}"
  "QCheckBox#custom_colors_checkbox_ {"
  " margin-left: 10px;"
  "}"
    );

// === LayerManagerWidget Styles === //
const QString StyleSheet::LAYERMANAGERWIDGET_C = QString::fromUtf8(
  "QScrollArea{"
  " background-color: rgb( " BACKGROUND_COLOR ") ;"
  "}"
  "QWidget#main_{"
  " background-color: rgb( " BACKGROUND_COLOR ") ;"
  " margin: 0px;"
  "}"
  // somehow this is a hack that just covers up the white border.
  // TODO figure out how to turn off the white border instead
  "QWidget#scrollAreaWidgetContents{"
  " border: 1px solid rgb( " BACKGROUND_COLOR ") ;"
  "}"
  );

// === LayerWidget Styles === //
// - LayerWidget - //
const QString StyleSheet::LAYERWIDGET_C = QString::fromUtf8(
  "QWidget#LayerWidget {"
  " background-color: rgb( " PALETTE_BACKGROUND_COLOR ") ;"
  " color: rgb( " FONT_COLOR ") ; "
  " border: none;"
  " border-radius: 3px;"
  " margin: 0px;"
  "}"
  "QWidget#header_{"
  " border-bottom: none;"
  "}"
  "QLabel#facade_widget_{ "
  " background-color: rgba(0, 0, 0, 0); "
  "}"

  "QFrame#iso_control_separator_line_{ "
  " background-color: rgb( " HOVER_COLOR ") ;"
  "}"

  "QWidget#buttons_widget_{ "
  " border-top: 1px solid rgb( " HOVER_COLOR ") ; "
  " margin-right: 5px;"
  "} "
  "QLineEdit#label_{"
  " text-align: left;"
  " color: rgb( " FONT_COLOR ") ;"
  " selection-background-color: rgb( " ACCENT_COLOR ") ; "
  " selection-color: rgb( " FONT_COLOR ") ; "
  " background-color: rgb( " PALETTE_BACKGROUND_COLOR ") ;"
  " border-radius: 3px;"
  " margin: 1px;"
  " outline: none;"
 "}"
  "QLineEdit#label_:focus{"
  " background-color: rgb( " FORM_BACKGROUND_COLOR ") ;"
  " border: none;"
  "}"
  );

// - ACTIVE - //
const QString StyleSheet::LAYER_WIDGET_BASE_ACTIVE_C = QString::fromUtf8(
  "QWidget#base_ {"
  " border: 3px solid rgb( " BORDER_COLOR ") ;"
  " border-top-width: 1px;"
  " border-top-color: rgb( " BORDER_COLOR ") ;"
  " border-radius: 3px;"
  " border-top-right-radius: 3px 1px;"
  " border-top-left-radius: 3px 1px;"
  " background-color: rgb( " ACCENT_COLOR ") ;"
  "}"
  );

const QString StyleSheet::LAYER_WIDGET_BASE_ACTIVE_IN_USE_C = QString::fromUtf8(
  "QWidget#base_{"
  " border: 3px solid rgba(73, 111, 160, 150);"
  " border-top-width: 1px;"
  " border-top-color: rgb( " BORDER_COLOR ") ;"
  " border-radius: 3px;"
  " border-top-right-radius: 3px 1px;"
  " border-top-left-radius: 3px 1px;"
  " background-color: rgb( " ACCENT_COLOR ") ;"
  "}");

const QString StyleSheet::LAYER_WIDGET_BASE_IN_USE_C = QString::fromUtf8(
  "QWidget#base_{"
  " border: 3px solid rgba(73, 111, 160, 150);"
  " border-top-width: 0px;"
  " border-radius: 3px;"
  " border-top-right-radius: 0px;"
  " border-top-left-radius: 0px;"
  " background-color: rgb( " HOVER_COLOR ") ;"
  "}");

// - INACTIVE - //
const QString StyleSheet::LAYER_WIDGET_BASE_INACTIVE_C = QString::fromUtf8(
  "QWidget#base_{"
  " background-color: rgb( " PALETTE_BACKGROUND_COLOR ") ;"
  " border: 3px solid rgb( " BORDER_COLOR ") ;"
  " border-top-width: 0px;"
  " border-radius: 3px;"
  " border-top-right-radius: 0px;"
  " border-top-left-radius: 0px;"
  "}");

const QString StyleSheet::LAYER_WIDGET_LABEL_INACTIVE_C = QString::fromUtf8(
  "QLineEdit#label_:!focus{"
  " background-color: rgb( " PALETTE_BACKGROUND_COLOR ") ;"
  "}");

const QString StyleSheet::LAYER_WIDGET_LABEL_ACTIVE_C = QString::fromUtf8(
  "QLineEdit#label_:!focus{"
  " background-color: rgb( " ACCENT_COLOR ") ;"
  "}");

const QString StyleSheet::LAYER_WIDGET_LABEL_ACTIVE_IN_USE_C = QString::fromUtf8(
  "QLineEdit#label_:!focus{"
  " background-color: rgb( " ACCENT_COLOR ") ;"
  "}");
  
const QString StyleSheet::LAYER_WIDGET_LABEL_IN_USE_C = QString::fromUtf8(
  "QLineEdit#label_:!focus{"
  " background-color: rgb( " HOVER_COLOR ") ;"
  "}");      
// - VISUAL_LOCKED - //
const QString StyleSheet::LAYER_WIDGET_BASE_LOCKED_C = QString::fromUtf8(
  "QWidget#base_ {"
  " border: 3px solid rgb( " SELECT_COLOR ") ;"
  " border-top-width: 0px;"
  " border-radius: 3px;"
  " border-top-right-radius: 0px;"
  " border-top-left-radius: 0px;"
  " background-color: rgb( " HOVER_COLOR ") ;"
  "}"
);
  
const QString StyleSheet::LAYER_WIDGET_LABEL_LOCKED_C = QString::fromUtf8(
  "QLineEdit#label_:!focus{"
  " color: gray;"
  " background-color: rgb( " HOVER_COLOR ") ;"
  "}");


// === LayerGroupWidget Styles === //
const QString StyleSheet::GROUP_WIDGET_BACKGROUND_ACTIVE_C = QString::fromUtf8(  
  "QWidget#group_header_ {"
  " background-color: rgb( " ACCENT_COLOR ") ;"
  " border: 3px solid rgb( " BORDER_COLOR ") ;"
  " border-radius: 3px;"
  " border-bottom: 0px solid transparent;"
  " border-bottom-right-radius:0px;"
  " border-bottom-left-radius:0px;"
  " color: white;"
  " padding: 1px;"
  "}"
  "QToolButton:checked:!hover {"
  " background-color: rgba(0,0,0,0);"
  " margin: 0 0 0 0;"
  " padding: 0 0 0 0;"
  "}"
    );
const QString StyleSheet::GROUP_WIDGET_BACKGROUND_INACTIVE_C = QString::fromUtf8(  
  "QWidget#group_header_ {"
  " background-color: rgb( " INACTIVE_COLOR ") ;"
  " border: 2px solid rgb( " BORDER_COLOR ") ;"
  " border-radius: 3px;"
  " border-bottom-width: 2px;"
  " border-bottom-right-radius:3px;"
  " border-bottom-left-radius:3px;"
  " color: white;"
  " padding: 1px;"
  "}"
    );
// === LayerResamplerWidget Styles === //
const QString StyleSheet::LAYER_RESAMPLER_C = QString::fromUtf8(
  "QDialog{"
  " background-color: rgb(" BACKGROUND_COLOR ");"
  " border: none;"
  "}"
  );

// - PushDragButton - //  
const QString StyleSheet::LAYER_PUSHDRAGBUTTON_C = QString::fromUtf8(
  "QPushButton#activate_button_{"
  " background-color: rgba(0, 0, 0, 0);"
  " border: 0px solid rgba(0, 0, 0, 0);"
  //" margin-left:1px;"
  " border-radius: 3px;"
  " color: white;"
  " margin: 0px;"
  " padding: 0px;"
  "}"
  "QPushButton#activate_button_:disabled{"
  " background-color: rgb( " HOVER_COLOR ") ;"
  " border: 0px solid rgba(0, 0, 0, 0);"
  " border-radius: 3px;"
  " color: gray;"
  " margin: 0px;"
  " padding: 0px;"
  "}");

const QString StyleSheet::GROUP_PUSHDRAGBUTTON_C = QString::fromUtf8(
  "QPushButton#activate_button_{"
  " background-color:rgba(0, 0, 0, 0);"
  " border-color: rgba(0, 0, 0, 0);"
  " border: none;"
  " height: 24px;"
  " text-align: left;"
  " color: white;"
  " margin: 0 0 0 0;"
  " padding: 0 0 0 0;"
  " font: bold;"
  "}"
  "QPushButton#activate_button_:pressed{"
  " background-color:rgba(0, 0, 0, 0);"
  " border: none;"
  " border-color: rgba(0, 0, 0, 0);"
  " color: gray;"
  " margin: 0 0 0 0;"
  " padding: 0 0 0 0;"
  "}"
  "QPushButton#activate_button_:disabled{"
  " background-color:rgb( " HOVER_COLOR ") ;"
  " border: none;"
  " border-color: rgba(0, 0, 0, 0);"
  " color: gray;"
  " margin: 0 0 0 0;"
  " padding: 0 0 0 0;"
  "}");

// - ViewerWidget - //
const QString StyleSheet::VIEWERWIDGET_C = QString::fromUtf8(
  "QObject#line_{"
  " background-color: rgb(" HOVER_COLOR ") ;"
  "}"
  "QWidget#toolbar_{"
  " border-top: 1px solid rgb(" HOVER_COLOR ") ;"
  "}"
  "QComboBox {"
  " background-color: rgb(" BACKGROUND_COLOR ") ;"
  " border-radius: 0px;"
  " color: rgb( " FONT_COLOR ") ;"
  " margin: 0px;"
  " padding: 0px 0px 0px 4px;"
  " border: 1px solid rgb(" BACKGROUND_COLOR ");"
  " width: 90px;"
  "}"
  "QComboBox QAbstractItemView{"
  " background-color:rgb( " PALETTE_BACKGROUND_COLOR ") ;"
  " border-radius: 0px;"
  " color: rgb( " FONT_COLOR ") ;"
  " padding: -2px;"
  " margin: 1px;"
  "}"
  "QComboBox:off {"
  " background-color: rgb(" BACKGROUND_COLOR ") ;"
  " border-radius: 0px;"
  " color: rgb( " FONT_COLOR ") ;"
  " margin: 0px;"
  " padding: 0px 0px 0px 4px;"
  " border: 1px solid rgb(" BACKGROUND_COLOR ");"
  " width: 90px;"
  "}"
  "QComboBox::drop-down{"
  " subcontrol-origin: padding; "
  " subcontrol-position: top right; "
  " border-color: rgba(0,0,0,0);"
  " border-radius: 0px;"
  " padding: 0px;"
  " background-color: rgb(" BACKGROUND_COLOR ") ;"
  "}"
  "QComboBox:!editable:unchecked, QComboBox:on{"
  " background-color: rgb( " SELECT_COLOR ") ;"
  " color: rgb( " FONT_COLOR ") ;"
  " border: none;"
  " border-radius: 0px;"
  "}"
  "QComboBox:checked:!hover{"
  " background-color:rgb( " SELECT_COLOR ") ;"
  " border: none;"
  "}"
  "QComboBox::down-arrow{"
  " border-color: rgba(0,0,0,0);"
  " border-radius: 0px;"
  " image: none;"
  " width: 0px;"
  "}"
  "QComboBox::down-arrow:on{"
  " top: 1px;"
  " left: 1px;"
  "}"
  "QComboBox:hover{"
  " border: 1px solid rgb(" SELECT_COLOR ");"
  "}"
  "QComboBox:!hover{"
  " border: 1px solid transparent;"
  "}"
  );
const QString StyleSheet::VIEWERSELECTED_C = QString::fromUtf8(
  "QWidget#border_{"
  " border-top: 3px solid rgb( " ACCENT_COLOR ") ;"
  " border-bottom: 3px solid rgb( " ACCENT_COLOR ") ;"
  " border-left: 3px solid rgb( " ACCENT_COLOR ") ;"
  " border-right: 3px solid rgb( " ACCENT_COLOR ") ;"
  "}");

const QString StyleSheet::VIEWERNOTSELECTED_C = QString::fromUtf8(
   "QWidget#border_{"
   "  border-top: 3px solid rgb(" INACTIVE_COLOR ");"
   "  border-bottom: 3px solid rgb(" INACTIVE_COLOR ");"
   "  border-left: 3px solid rgb(" INACTIVE_COLOR ");"
   "  border-right: 3px solid rgb(" INACTIVE_COLOR ");"
   "}");
const QString StyleSheet::VIEWERWIDGET_SINGLELINE_C = QString::fromUtf8(
  "QWidget#buttonbar_{"
  " border-bottom: none ;"
  "}"
  "QWidget#viewer_mode_holder_{"
  " border-bottom: none ;"
  "}"
  );
const QString StyleSheet::VIEWERWIDGET_DOUBLELINE_C = QString::fromUtf8(
  "QWidget#buttonbar_{"
  " border-bottom: 1px solid rgb(" HOVER_COLOR ") ;"
  "}"
  "QWidget#viewer_mode_holder_{"
  " border-bottom: 1px solid rgb(" HOVER_COLOR ") ;"
  "}"
  );


const QString StyleSheet::LAYERIO_C = QString::fromUtf8(
  "QPushButton#mask_single_button{"
  " background-color: transparent;"
  " color: rgb( " FONT_COLOR ") ;"
  " border-radius: 3px;"
  " border: 1px ridge rgba(106, 106, 112, 255);"
  " margin:0px;"
  " padding: 0px;"
  "}"
  "QPushButton#mask_single_button:hover{"
  " background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
  "   stop:0 rgba(98, 97, 103, 150), "
  "   stop:0.253769 rgba(11, 11, 11, 150), "
  "   stop:1 rgba(24, 24, 26, 150));"
  "}"
  "QPushButton#mask_single_button:pressed{"
  " background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
  "   stop:0 rgba(10, 10, 12, 150), "
  "   stop:0.753769 rgba(81,80,87, 150), "
  "   stop:1 rgba(96, 95, 100, 150));"
  " border: 1px inset rgba(106, 106, 112, 255);"
  "}"
  "QPushButton#mask_single_button:checked{"
  " background-color: transparent;"
  " border: 3px solid rgba(" ACCENT_COLOR ", 255);"
  "}"
  "QPushButton#data_volume_button{"
  " background-color: transparent;"
  " color: rgb( " FONT_COLOR ") ;"
  " border-radius: 3px;"
  " border: 1px ridge rgba(106, 106, 112, 255);"
  " margin:0px;"
  " padding: 0px;"
  "}"
  "QPushButton#data_volume_button:hover{"
  " background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
  "   stop:0 rgba(98, 97, 103, 150), "
  "   stop:0.253769 rgba(11, 11, 11, 150), "
  "   stop:1 rgba(24, 24, 26, 150));"
  "}"
  "QPushButton#data_volume_button:pressed{"
  " background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
  "   stop:0 rgba(10, 10, 12, 150), "
  "   stop:0.753769 rgba(81,80,87, 150), "
  "   stop:1 rgba(96, 95, 100, 150));"
  " border: 1px inset rgba(106, 106, 112, 255);"
  "}"
  "QPushButton#data_volume_button:checked{"
  " background-color: transparent;"
  " border: 3px solid rgba(" ACCENT_COLOR ", 255);"
  "}"
  "QPushButton#mask_1234_button{"
  " background-color: transparent;"
  " color: rgb( " FONT_COLOR ") ;"
  " border-radius: 3px;"
  " border: 1px ridge rgba(106, 106, 112, 255);"
  " margin:0px;"
  " padding: 0px;"
  "}"
  "QPushButton#mask_1234_button:hover{"
  " background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
  "   stop:0 rgba(98, 97, 103, 150), "
  "   stop:0.253769 rgba(11, 11, 11, 150), "
  "   stop:1 rgba(24, 24, 26, 150));"
  "}"
  "QPushButton#mask_1234_button:pressed{"
  " background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
  "   stop:0 rgba(10, 10, 12, 150), "
  "   stop:0.753769 rgba(81,80,87, 150), "
  "   stop:1 rgba(96, 95, 100, 150));"
  " border: 1px inset rgba(106, 106, 112, 255);"
  "}"
  "QPushButton#mask_1234_button:checked{"
  " background-color: transparent;"
  " border: 3px solid rgba(" ACCENT_COLOR ", 255);"
  "}"
  "QPushButton#mask_1248_button{"
  " background-color: transparent;"
  " color: rgb( " FONT_COLOR ") ;"
  " border-radius: 3px;"
  " border: 1px ridge rgba(106, 106, 112, 255);"
  " margin:0px;"
  " padding: 0px;"
  "}"
  "QPushButton#mask_1248_button:hover{"
  " background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
  "   stop:0 rgba(98, 97, 103, 150), "
  "   stop:0.253769 rgba(11, 11, 11, 150), "
  "   stop:1 rgba(24, 24, 26, 150));"
  "}"
  "QPushButton#mask_1248_button:pressed{"
  " background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
  "   stop:0 rgba(10, 10, 12, 150), "
  "   stop:0.753769 rgba(81,80,87, 150), "
  "   stop:1 rgba(96, 95, 100, 150));"
  " border: 1px inset rgba(106, 106, 112, 255);"
  "}"
  "QPushButton#mask_1248_button:checked{"
  " background-color: transparent;"
  " border: 3px solid rgba(" ACCENT_COLOR ", 255);"
  "}"
  "QWidget#data_{"
  " background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
  "   stop:0 rgba(100, 99, 106, 255), "
  "   stop:0.15 rgba(81,80,87,255), "
  "   stop:0.3 rgba(22, 22, 22, 255), "
  "   stop:0.76 rgba(38, 38, 40, 255));"
  " color: rgba(" FONT_COLOR ",255);"
"}"
"QWidget#single_mask_{"
" background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
  "   stop:0 rgba(100, 99, 106, 255), "
  "   stop:0.15 rgba(81,80,87,255), "
  "   stop:0.3 rgba(22, 22, 22, 255), "
  "   stop:0.76 rgba(38, 38, 40, 255));"
  " color: rgba(" FONT_COLOR ",255);"
"}"
"QWidget#bitplane_mask_{"
" background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
  "   stop:0 rgba(100, 99, 106, 255), "
  "   stop:0.15 rgba(81,80,87,255), "
  "   stop:0.3 rgba(22, 22, 22, 255), "
  "   stop:0.76 rgba(38, 38, 40, 255));"
  " color: rgba(" FONT_COLOR ",255);"
"}"
"QWidget#label_mask_{"
" background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
  "   stop:0 rgba(100, 99, 106, 255), "
  "   stop:0.15 rgba(81,80,87,255), "
  "   stop:0.3 rgba(22, 22, 22, 255), "
  "   stop:0.76 rgba(38, 38, 40, 255));"
  " color: rgba(" FONT_COLOR ",255);"
"}"
"QWidget#scanning_file_{"
" background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
  "   stop:0 rgba(100, 99, 106, 255), "
  "   stop:0.15 rgba(81,80,87,255), "
  "   stop:0.3 rgba(22, 22, 22, 255), "
  "   stop:0.76 rgba(38, 38, 40, 255));"
  " color: rgba(255,255,255,255);"
" border-radius: 3px;"
" border: 1px solid  rgb( 215, 215, 215 );"
"}"
"QWidget#data_volume_icon_widget_{"
" background-color: rgb( " ACCENT_COLOR ") ;"
  " color: rgba(" FONT_COLOR ",255);"
" border-radius: 3px;"
" border: 1px solid rgb(130, 130, 130);"
"}"
"QWidget#single_mask_icon_widget_{"
" background-color: rgb( " ACCENT_COLOR ") ;"
  " color: rgba(" FONT_COLOR ",255);"
" border-radius: 3px;"
" border: 1px solid rgb(130, 130, 130);"
"}"
"QWidget#series_of_masks_1234_icon_widget_{"
" background-color: rgb( " ACCENT_COLOR ") ;"
  " color: rgba(" FONT_COLOR ",255);"
" border-radius: 3px;"
" border: 1px solid rgb(130, 130, 130);"
"}"
"QWidget#series_of_masks_1248_icon_widget_{"
" background-color: rgb( " ACCENT_COLOR ") ;"
  " color: rgba(" FONT_COLOR ",255);"
" border-radius: 3px;"
" border: 1px solid rgb(130, 130, 130);"
"}"
"QToolButton#data_button_{"
" border: 1px solid rgba( 0, 0, 0, 0 );"
" background-color: rgba( 0, 0, 0, 0 );"
"}"
"QToolButton#data_button_:pressed{"
" border: 1px solid rgba( 0, 0, 0, 0 );"
" background-color: rgba( 0, 0, 0, 0 );"
"}"
"QToolButton#single_mask_button_{"
" border: 1px solid rgba( 0, 0, 0, 0 );"
" background-color: rgba( 0, 0, 0, 0 );"
"}"
"QToolButton#single_mask_button_:pressed{"
" border: 1px solid rgba( 0, 0, 0, 0 );"
" background-color: rgba( 0, 0, 0, 0 );"
"}"
"QToolButton#series_1248_button_{"
" border: 1px solid rgba( 0, 0, 0, 0 );"
" background-color: rgba( 0, 0, 0, 0 );"
"}"
"QToolButton#series_1248_button_:pressed{"
" border: 1px solid rgba( 0, 0, 0, 0 );"
" background-color: rgba( 0, 0, 0, 0 );"
"}"
"QToolButton#series_1234_button_{"
" border: 1px solid rgba( 0, 0, 0, 0 );"
" background-color: rgba( 0, 0, 0, 0 );"
"}"
"QToolButton#series_1234_button_:pressed{"
" border: 1px solid rgba( 0, 0, 0, 0 );"
" background-color: rgba( 0, 0, 0, 0 );"
"}"
);

const QString StyleSheet::PROVENANCE_LIST_HEADER_C = QString::fromUtf8(
  "QWidget#header_bkg_{"
  " background-color: rgb( " ACCENT_COLOR ") ;"
  " border-radius: 3px;"
  " border: 3px solid rgb( " BORDER_COLOR ") ;"
  " border-bottom-width: 0px;"
  " border-bottom-right-radius: 0px;"
  " border-bottom-left-radius: 0px;"
  " margin: 0px;"
  "}"
  "QWidget#prov_content_{"
  " border: 3px solid rgb( " BORDER_COLOR ") ;"
  " border-radius: 3px;"
  " border-top-width: 0px;"
  " border-top-right-radius: 0px;"
  " border-top-left-radius: 0px;"
  " background-color: rgb( " PALETTE_BACKGROUND_COLOR ") ;"
  " margin: 0px;"
  "}"
  "QWidget#provenance_list_{"
  " border: 3px solid rgb( " BORDER_COLOR ") ;"
  " border-radius: 3px;"
  " border-top-width: 0px;"
  " border-top-right-radius: 0px;"
  " border-top-left-radius: 0px;"
  " border-bottom-width: 0px;"
  " border-bottom-right-radius: 0px;"
  " border-bottom-left-radius: 0px;"
  " margin: 0px;"
  "}"
);

  const QString StyleSheet::SPLASHSCREEN_C = QString::fromUtf8(
  "SplashScreen#splashscreen{"
  " background-color: transparent; "
  "}"
);

  const QString StyleSheet::PREFERENCES_C = QString::fromUtf8(
    "QWidget#prefs_tabs_ QGroupBox {"
    " background-color: rgb( " PALETTE_BACKGROUND_COLOR ") ;"
    "}"
);

  const QString StyleSheet::SHORTCUTS_C = QString::fromUtf8(
    "QWidget#scrollAreaWidgetContents {"
    " background-color: rgb( " BACKGROUND_COLOR ") ;"
    "}"
    "QWidget#scrollAreaWidgetContents_2 {"
    " background-color: rgb( " BACKGROUND_COLOR ") ;"
    "}"
    "QWidget#scrollAreaWidgetContents_3 {"
    " background-color: rgb( " BACKGROUND_COLOR ") ;"
    "}"
    "QWidget#scrollAreaWidgetContents_4 {"
    " background-color: rgb( " BACKGROUND_COLOR ") ;"
    "}"
    "QWidget#active_tool_shortcuts_ QScrollArea {"
    " border: 1px solid white;"
    "}"
    "QWidget#active_tool_shortcuts_ QWidget {"
    " background-color: rgb( " BACKGROUND_COLOR ") ;"
    "}"
    );

  const QString StyleSheet::SEGMENTATION_EXPORT_C = QString::fromUtf8(
   "QFrame {"
   " background-color: rgb( " PALETTE_BACKGROUND_COLOR " );"
   "}"
   "QScrollArea {"
   " background-color: rgb( " PALETTE_BACKGROUND_COLOR " );"
   "}"
   "QWidget#group_with_masks_tree_ {"
   " background-color: rgb( " PALETTE_BACKGROUND_COLOR " );"
   "}"
   "QWidget#layers_ {"
   " background-color: rgb( " PALETTE_BACKGROUND_COLOR " );"
   "}"
   "QFrame#layer_line_{ "
   " background-color: rgb( " HOVER_COLOR ") ;"
   "}"
  );

  const QString StyleSheet::QTLAYERLISTWIDGET_VALID_C = QString::fromUtf8(
    " background-color: transparent;"
  );
  const QString StyleSheet::QTLAYERLISTWIDGET_INVALID_C = QString::fromUtf8(
    " background-color: rgb( " ALERT_BACKGROUND_COLOR ") ;"
  );

  const QString StyleSheet::TRISTATE_UNCHECKED_C = QString::fromUtf8(
    "QToolButton{"
    " background-color: transparent;"
    " border-width: 2px;"
    " border-radius: 2px;"
    "}"
    );
  const QString StyleSheet::TRISTATE_INTERMEDIATE_C = QString::fromUtf8(
    "QToolButton{"
    " background-color: rgb( " HOVER_COLOR ") ;"
    " border-width: 2px;"
    " border-radius: 2px;"
    "}"
    );
  const QString StyleSheet::TRISTATE_CHECKED_C = QString::fromUtf8(
    "QToolButton{"
    " background-color: rgb( " SELECT_COLOR ") ;"
    " border-width: 2px;"
    " border-radius: 2px;"
    "}"
    );

  const QString StyleSheet::SPEEDLINE_TOOL_C = QString::fromUtf8(
    "QLabel#message_1_ {"
    " color: rgb(" FONT_COLOR ");"
    " font: bold;"
    "}"
    "QWidget#message_data_layer_alert_ {"
    " border-radius: 3px;"
    " background-color: rgb(" ALERT_BACKGROUND_COLOR ");"
    "}"
    "QWidget#message_mask_alert_ {"
    " border-radius: 3px;"
    " background-color: rgb(" ALERT_BACKGROUND_COLOR ");"
    "}"
    );

  const QString StyleSheet::ACCENT_COLOR_C = QString::fromUtf8(
    ACCENT_HEX_COLOR );
  const QString StyleSheet::CRITICAL_ERROR_COLOR_C = QString::fromUtf8(
    CRITICAL_ERROR_HEX_COLOR );
  const QString StyleSheet::ERROR_COLOR_C = QString::fromUtf8(
    ERROR_HEX_COLOR );
  const QString StyleSheet::WARNING_COLOR_C = QString::fromUtf8(
    WARNING_HEX_COLOR );
  const QString StyleSheet::MESSAGE_COLOR_C = QString::fromUtf8(
    MESSAGE_HEX_COLOR );
  const QString StyleSheet::SUCCESS_COLOR_C = QString::fromUtf8(
    SUCCESS_HEX_COLOR );
  const QString StyleSheet::DEBUG_COLOR_C = QString::fromUtf8(
    DEBUG_COLOR );
}  // end namespace Seg3D
